### ISSUE TITLE
Error while installing PMS in Linux using docker

### ISSUE THREAD

**Issue by asitemade4u** [Volmarg/personal-management-system#61] opened 2021-05-05 14:52 UTC
Hi,
I am eager to use PMS which fits a personal project perfectly.
Unfortunately I have an issue when opening the application.

1. My environment: Debian 10, last version of docker
2. I am quite familiar with docker and have followed your instructions very precisely -- I know they are intended for docker/Windows, but I assumed they would work for docker/Linux too
3. When I try to connect remotely to PMS (it is installed on a server @192.168.1.44), here is the error I get:

![Screenshot-20210505-105053](https://user-images.githubusercontent.com/11460106/117161343-d3300400-ad8f-11eb-946f-3194e046b7f1.png)

Please help.
Best,
Stephen

**Comment by Volmarg** [comment] 2021-05-05 15:58
Did You used the auto installer inside docker? 
It should do all the privileges related things.

Anyway:
- login to the linux in docker,
- go to the project directory there, should be something like `var/www/` (depending on config),
- inside the `www` call:
   - `chmod 755 projectDir -R` (should be enough)
   - `chown www-data:www-data projectDir` -R,
   - go to `projectDir` and call
     -  `bin/console cache:clear`
     - `bin/console cache:warmup`

**Comment by asitemade4u** [comment] 2021-05-05 16:18
Hi Daryush,

Thanks for the prompt response.

To clean the slate, I have decided to reinstall PMS anew.
There is a discrepancy between the documentation and the [install 
process in 
docker](https://volmarg.github.io/docs/general/installation/docker/windows). 
At point 7, when installing apcu, it says I should get `Extension apcu 
enabled in php.ini`

However what I get is a notice saying:

```

configuration option "php_ini" is not set to php.ini location
You should add "extension=apcu.so" to php.ini

```

Maybe this is also a cause of things not going well.

How do I fix it?

**Comment by asitemade4u** [comment] 2021-05-05 16:23
What is weird though is that I checked in `/usr/local/etc/php/conf.d/php.ini` and the line `extension=apcu.so` is there indeed.
Goig on with the install then.

**Comment by Volmarg** [comment] 2021-05-05 16:36
Its not apcu as it causes other errors when building cache in cli i mean should not be Able to build it at all - go with my commands first. You might save time.

Then i can think about the apcu notice.

**Comment by asitemade4u** [comment] 2021-05-05 17:14
I was just mentioning the fact for other users not to worry about.
I followed the instructions and now I get this series of errors and cannot connect (see PDF attached).

[error.pdf](https://github.com/Volmarg/personal-management-system/files/6428985/error.pdf)

**Comment by asitemade4u** [comment] 2021-05-05 17:15
Don't you think it would be a good idea to create a fully constituted docker image now that your application is stable? Would simplify installation a lot.

**Comment by Volmarg** [comment] 2021-05-05 17:21
Docker image is there, provided by other ppl - they tested it on linux. I tested it also with guide on windows - it works.

Your error however states that table in database is simply missing.

Did You called the step **8** from: https://volmarg.github.io/docs/general/installation/docker/windows?

I see the code right before me and it should create the database with base tables:
![image](https://user-images.githubusercontent.com/37488679/117182633-e1edd980-add6-11eb-8745-d944f447c3e9.png)

I'm not familiar with **Docker** thus it exists only thx to contribution of other ppl. This issue here is imho related to Your state of database. 

Make sure it has tables at all, and do ensure that step **8** was called.

**Comment by Volmarg** [comment] 2021-05-05 17:23
However this is not bad idea to extend the docker setting file to call the composer + autoinstaller. Should work since it's all preconfigured - but this won't happen soon. So for now this has to be solved by following current state of guide.

**Comment by asitemade4u** [comment] 2021-05-05 19:09
Dear Daryusz,
I have cleaned the docker state once again and redone the FULL install using docker on Debian. It yielded the exact error.
My reasonable conclusion is that there is an error within the dockerfile. Maybe you could ask the person who helped you set it up to be in touch with me in order to fix it.
Now, as I am ujsing a virtual machine on Proxmox, I am not opposed to an installation in a full fledged virtual machine.
However, I have tried the procedure described [here}(https://volmarg.github.io/docs/general/installation/linux). Despite being a seasoned IT engineer, I found it too complex and abandoned the deployment at midway.
Maybe an all-encompassing script would be a great idea -- I recently installed SaltStack and Zabbix that way and it went very well.
Best,
Stephen

**Comment by Volmarg** [comment] 2021-05-06 13:18
I will test the docker file myself in free time in weekend.

And thx for info regarding the installation issues - i might think of it. I know other ppl use the project.

**Comment by asitemade4u** [comment] 2021-05-06 13:19
Thank you very much.

**Comment by Volmarg** [comment] 2021-05-06 13:22
Hmm while now we have to handle it this Way You gave me an idea to make an installer GUI like wordpress has - as an altrrnative

**Comment by asitemade4u** [comment] 2021-05-06 13:26
Yes, or even a simpler one as Zabbix does -- their configuration page 
comes in really handy: https://www.zabbix.com/download

**Comment by Volmarg** [comment] 2021-05-08 14:47
Yeap, that's a bug of mine, i can confirm that.

![image](https://user-images.githubusercontent.com/37488679/117543373-d7bd1c80-b01c-11eb-9d59-a11ab3ff10d2.png)

Maybe gonna fix that tommorow in free moment.
But if You want to install that today then temporary solution is to open:
`src/AutoInstaller.php`,

replace all `php7.4 ` string occurences in called commands like `php7.4 bin/console doctrine:database:drop -n --force`
into `php bin/console doctrine:database:drop -n --force`

**Comment by BOOM21** [comment] 2021-05-09 10:18
I submitted a pull-request which should fix the issue, hope I can save you this little time, ran into the same error today. I've tested it now and it seems to be fixed with no further issue.

**Comment by Volmarg** [comment] 2021-05-09 10:27
Hey, thx.

I saw that, but it's not so simple as that. I've created that bug because the installed won't work outside the docker otherwise.

I've got few php versions installed locally, so caling `php ...` causes error as my default `php` points to `8.0`.

Docker has no `php 7.4` but just `php` thus it works.

What I'm thinking of is more like "Passing parameter" to autoinstaller methods like this:

```
if docker -> use php
else php7.4
```

This would be enough for now but I still need to fix the case where user can be running project on either `php-fpm` or `apache`.

**Comment by Volmarg** [comment] 2021-05-10 16:06
@asitemade4u This is now fixed in: https://github.com/Volmarg/personal-management-system/commit/aebfe4dd65fc2752c98a788bc77f8d84db5d8978

I'm not closing this issue as I got other one in docker - doctrine metadata cache is not building up due to missing apcu (even though it's installed).

**Comment by Volmarg** [comment] 2021-05-10 16:34
`apc cache issue` fixed in :https://github.com/Volmarg/personal-management-system/commit/b1cef1144f88c6bc2951271c8e995f7199e41eb6 

@BOOM21 can You please tell me if You managed to register user in GUI without any issues? This doesn't seems to be working in docker - got success but no entries in DB.

**Comment by Volmarg** [comment] 2021-05-16 06:30
Closing due to missing response.

**Closed by Volmarg** 2021-05-16 06:30 UTC
